import { describe, it, expect } from "vitest";
import { parseLLMOutput, ParseOutputError } from "../transpile/output-parser.js";

const VALID_SKILL_MD = `---
name: my_workflow
description: Does something useful.
metadata: {"openclaw":{"requires":{"bins":["node"],"env":["MY_API_KEY"]}}}
---

# My Workflow Skill

Use this skill to run the workflow.

## Usage
\`\`\`bash
node {baseDir}/skill.ts --input "$INPUT"
\`\`\`
`;

const VALID_SKILL_TS = `#!/usr/bin/env node
// My Workflow — generated by n8n-to-claw
import { env } from "node:process";

const apiKey = env["MY_API_KEY"];
if (!apiKey) {
  console.error("MY_API_KEY is not set");
  process.exit(1);
}

console.log("Running workflow with key:", apiKey.slice(0, 4) + "...");
`;

const VALID_LLM_OUTPUT = `\`\`\`skill-md
${VALID_SKILL_MD}\`\`\`

\`\`\`typescript
${VALID_SKILL_TS}\`\`\``;

describe("parseLLMOutput()", () => {
  it("parses a well-formed output", () => {
    const result = parseLLMOutput(VALID_LLM_OUTPUT);
    expect(result.skillMd).toContain("name: my_workflow");
    expect(result.skillTs).toContain("MY_API_KEY");
  });

  it("throws if skill-md block is missing", () => {
    const output = `\`\`\`typescript\n${VALID_SKILL_TS}\`\`\``;
    expect(() => parseLLMOutput(output)).toThrow(ParseOutputError);
  });

  it("throws if typescript block is missing", () => {
    const output = `\`\`\`skill-md\n${VALID_SKILL_MD}\`\`\``;
    expect(() => parseLLMOutput(output)).toThrow(ParseOutputError);
  });

  it("throws if SKILL.md lacks frontmatter", () => {
    const badSkillMd = `# No Frontmatter\n\nJust text.`;
    const output = `\`\`\`skill-md\n${badSkillMd}\n\`\`\`\n\`\`\`typescript\n${VALID_SKILL_TS}\`\`\``;
    expect(() => parseLLMOutput(output)).toThrow(ParseOutputError);
  });

  it("accepts markdown/md as fallback fence tag for SKILL.md", () => {
    const output = `\`\`\`markdown\n${VALID_SKILL_MD}\`\`\`\n\n\`\`\`typescript\n${VALID_SKILL_TS}\`\`\``;
    const result = parseLLMOutput(output);
    expect(result.skillMd).toBeTruthy();
  });

  it("accepts ts as fallback fence tag for skill.ts", () => {
    const output = `\`\`\`skill-md\n${VALID_SKILL_MD}\`\`\`\n\n\`\`\`ts\n${VALID_SKILL_TS}\`\`\``;
    const result = parseLLMOutput(output);
    expect(result.skillTs).toBeTruthy();
  });

  it("is tolerant of LLM preamble text before the blocks", () => {
    const output = `Here is the generated skill:\n\n${VALID_LLM_OUTPUT}\n\nLet me know if you need changes!`;
    const result = parseLLMOutput(output);
    expect(result.skillMd).toContain("name: my_workflow");
    expect(result.skillTs).toContain("MY_API_KEY");
  });

  it("throws if typescript block is suspiciously short", () => {
    const output = `\`\`\`skill-md\n${VALID_SKILL_MD}\`\`\`\n\n\`\`\`typescript\nshort\`\`\``;
    expect(() => parseLLMOutput(output)).toThrow(ParseOutputError);
  });

  it("handles nested triple-backtick fences inside code blocks", () => {
    const tsWithNestedFence = `#!/usr/bin/env node
// Usage:
// \`\`\`bash
// node skill.ts arg1
// \`\`\`
import { env } from "node:process";
const apiKey = env["MY_API_KEY"];
if (!apiKey) {
  console.error("MY_API_KEY is not set");
  process.exit(1);
}
console.log("Running with key:", apiKey.slice(0, 4) + "...");
`;
    const output = `\`\`\`skill-md\n${VALID_SKILL_MD}\`\`\`\n\n\`\`\`typescript\n${tsWithNestedFence}\`\`\``;
    const result = parseLLMOutput(output);
    expect(result.skillTs).toContain("node skill.ts arg1");
    expect(result.skillTs).toContain("MY_API_KEY");
  });
});
