#!/usr/bin/env node
// notify_slack_on_postgres — generated by n8n-to-claw
// Polls Postgres for new event rows and posts them to Slack.
import { execSync } from "node:child_process";
import { env } from "node:process";

const connStr = env["POSTGRES_CONNECTION_STRING"];
const webhookUrl = env["SLACK_WEBHOOK_URL"];

if (!connStr) {
  console.error("POSTGRES_CONNECTION_STRING is not set");
  process.exit(1);
}
if (!webhookUrl) {
  console.error("SLACK_WEBHOOK_URL is not set");
  process.exit(1);
}

const query =
  "SELECT id, type, created_at FROM events WHERE created_at > NOW() - INTERVAL '5 minutes'";

let rows: Array<{ id: string; type: string; created_at: string }>;
try {
  const raw = execSync(`psql "${connStr}" -t -A -F'|' -c "${query}"`, {
    encoding: "utf-8",
  });
  rows = raw
    .trim()
    .split("\n")
    .filter(Boolean)
    .map((line) => {
      const [id = "", type = "", created_at = ""] = line.split("|");
      return { id, type, created_at };
    });
} catch (err: unknown) {
  console.error("Postgres query failed:", err instanceof Error ? err.message : String(err));
  process.exit(1);
}

if (rows.length === 0) {
  console.log("No new rows.");
  process.exit(0);
}

for (const row of rows) {
  const text = `${row.id} — new event: ${row.type} at ${row.created_at}`;
  const body = JSON.stringify({ text });

  const result = execSync(
    `curl -s -X POST -H 'Content-Type: application/json' -d '${body}' '${webhookUrl}'`,
    { encoding: "utf-8" }
  );
  console.log("Slack response:", result.trim());
}
