#!/usr/bin/env node
// github_pr_review_notifier — generated by n8n-to-claw
// Posts a Slack message when a GitHub PR review is submitted.
import { request } from "node:https";
import { env } from "node:process";

const slackToken = env["SLACK_BOT_TOKEN"];
if (!slackToken) {
  console.error("SLACK_BOT_TOKEN is not set");
  process.exit(1);
}

// Read the webhook payload from stdin
const chunks: Buffer[] = [];
for await (const chunk of process.stdin) {
  chunks.push(chunk as Buffer);
}
const payload = JSON.parse(Buffer.concat(chunks).toString()) as Record<string, unknown>;

// Branch: only handle "submitted" reviews (n8n IF node equivalent)
const action = payload["action"];
if (action !== "submitted") {
  console.log(`Skipped: action is "${action}", not "submitted".`);
  process.exit(2);
}

// Extract fields (n8n Set node equivalent)
const review = payload["review"] as Record<string, unknown> | undefined;
const pr = payload["pull_request"] as Record<string, unknown> | undefined;
const reviewer = (review?.["user"] as Record<string, unknown> | undefined)?.["login"] ?? "unknown";
const state = review?.["state"] ?? "unknown";
const prNumber = pr?.["number"] ?? "?";
const prTitle = pr?.["title"] ?? "Untitled PR";
const prUrl = pr?.["html_url"] ?? "";

const text = `${reviewer} reviewed PR #${prNumber}: *${state}*\n${prTitle}\n${prUrl}`;

// Post to Slack (n8n Slack node equivalent)
function postSlack(channel: string, message: string): Promise<string> {
  return new Promise((resolve, reject) => {
    const body = JSON.stringify({ channel, text: message });
    const req = request(
      "https://slack.com/api/chat.postMessage",
      {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${slackToken}`,
        },
      },
      (res) => {
        const parts: Buffer[] = [];
        res.on("data", (d: Buffer) => parts.push(d));
        res.on("end", () => resolve(Buffer.concat(parts).toString()));
      }
    );
    req.setTimeout(10_000, () => {
      req.destroy();
      reject(new Error("Slack API request timed out"));
    });
    req.on("error", reject);
    req.end(body);
  });
}

const result = await postSlack("#code-reviews", text);
const parsed = JSON.parse(result) as Record<string, unknown>;
if (parsed["ok"] !== true) {
  console.error("Slack API error:", parsed["error"] ?? result);
  process.exit(1);
}
console.log(`Posted to #code-reviews: ${reviewer} ${state} PR #${prNumber}`);
