#!/usr/bin/env node
// daily_hacker_news_digest — generated by n8n-to-claw
// Fetches top HN stories and sends an email digest.
import { request as httpsRequest } from "node:https";
import { request as httpRequest } from "node:http";
import { createTransport } from "node:net";
import { env } from "node:process";

const smtpHost = env["SMTP_HOST"];
const smtpPort = env["SMTP_PORT"];
const smtpUser = env["SMTP_USER"];
const smtpPass = env["SMTP_PASS"];
const toEmail = env["DIGEST_TO_EMAIL"];

for (const [name, val] of Object.entries({ SMTP_HOST: smtpHost, SMTP_PORT: smtpPort, SMTP_USER: smtpUser, SMTP_PASS: smtpPass, DIGEST_TO_EMAIL: toEmail })) {
  if (!val) {
    console.error(`${name} is not set`);
    process.exit(1);
  }
}

function get(url: string): Promise<string> {
  const doRequest = url.startsWith("https") ? httpsRequest : httpRequest;
  return new Promise((resolve, reject) => {
    const req = doRequest(url, (res) => {
      const chunks: Buffer[] = [];
      res.on("data", (d: Buffer) => chunks.push(d));
      res.on("end", () => resolve(Buffer.concat(chunks).toString()));
    });
    req.setTimeout(10_000, () => { req.destroy(); reject(new Error("Request timed out")); });
    req.on("error", reject);
    req.end();
  });
}

// Fetch top story IDs
const topIdsRaw = await get("https://hacker-news.firebaseio.com/v0/topstories.json");
const topIds = (JSON.parse(topIdsRaw) as number[]).slice(0, 10);

// Fetch each story's details
interface Story { title: string; url?: string; score: number; descendants?: number; id: number }
const stories: Story[] = [];
for (const id of topIds) {
  const raw = await get(`https://hacker-news.firebaseio.com/v0/item/${id}.json`);
  stories.push(JSON.parse(raw) as Story);
}

// Format the digest (n8n Code node equivalent)
const today = new Date().toISOString().slice(0, 10);
const lines = stories.map((s, i) =>
  `${i + 1}. ${s.title} (${s.score} points)\n   ${s.url ?? `https://news.ycombinator.com/item?id=${s.id}`}\n   ${s.descendants ?? 0} comments`
);
const digest = lines.join("\n\n");

console.log(`HN Digest — ${today}\n\n${digest}`);

// TODO: Send email via SMTP
// The n8n emailSend node uses SMTP credentials. A full SMTP client
// implementation requires the nodemailer package or a raw net/tls socket.
// For now, log the digest and print instructions.
console.error(`\nTo send this digest, pipe to a mail command:`);
console.error(`  node skill.ts | mail -s "HN Digest ${today}" ${toEmail}`);
